
stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://localhost:2375/

before_script:
  - echo "Starting CI/CD process..."

build_app:
  stage: build
  script:
    - docker-compose -f docker-compose.yml build

deploy_app:
  stage: deploy
  script:
    - docker-compose -f docker-compose.yml down
    - docker-compose -f docker-compose.yml up -d
  only:
    - main
  tags:
    - ec2
