version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    hostname: backend
    ports:
      - "5000:5000"
    expose:
      - "5000"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/hello"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: ./frontend
      target: build
    container_name: frontend
    networks:
      - app-network

  nginx:
    build: ./nginx
    container_name: nginx
    hostname: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
